language: python
sudo: false
python:
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get install pandoc
  - pip install --upgrade pip
  - pip install codecov
install:
  - pip install -r requirements-dev.txt
  - pip install -e .
script:
  - make test
after_success:
  - codecov
