language: python
sudo: required
services:
  - docker
python:
  - "3.4"
  - "3.5"
addons:
  apt_packages:
    - pandoc
before_install:
  - pip install --upgrade pip
  - pip install codecov
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .
script:
  - make test
after_success:
  - codecov
