language: python
sudo: required
services:
  - docker
python:
  - "3.6"
before_install:
  - sudo apt-get install xvfb libfontconfig wkhtmltopdf imagemagick tex-common texlive -y
  - pip install --upgrade pip
  - pip install codecov
  - sudo bash latest_pandoc.sh  # install latest pandoc release
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .
script:
  - xvfb-run make test
after_success:
  - codecov
