language: python
sudo: required
services:
  - docker
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - pip install --upgrade pip
  - pip install codecov
  - sudo bash latest_pandoc.sh  # install latest pandoc release
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .
script:
  - make test
after_success:
  - codecov
